framework:
    default_locale: fr
    translator:
        paths:
            - '%kernel.project_dir%/translations/en' # Dossier pour les traductions en anglais
            - '%kernel.project_dir%/translations/fr' 
        fallbacks:
            - fr
        providers:
